# This rule is not used by the project prescaler itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to prescaler.altuhov.su resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: prescaler
    app.kubernetes.io/managed-by: kustomize
  name: prescale-viewer-role
rules:
- apiGroups:
  - prescaler.altuhov.su
  resources:
  - prescales
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - prescaler.altuhov.su
  resources:
  - prescales/status
  verbs:
  - get
