# This rule is not used by the project prescaler itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the prescaler.altuhov.su.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: prescaler
    app.kubernetes.io/managed-by: kustomize
  name: prescale-editor-role
rules:
- apiGroups:
  - prescaler.altuhov.su
  resources:
  - prescales
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - prescaler.altuhov.su
  resources:
  - prescales/status
  verbs:
  - get
