apiVersion: prescaler.altuhov.su/v1
kind: Prescale
metadata:
  labels:
    app.kubernetes.io/name: prescaler
    app.kubernetes.io/managed-by: kustomize
  name: prescale-sample
spec:
  targetHpaName: nginx-project
  schedule: "50,54 * * * *"
  percent: 50
  suspend: false
