apiVersion: prescaler.altuhov.su/v1
kind: Prescale
metadata:
  labels:
    app.kubernetes.io/name: prescaler
    app.kubernetes.io/managed-by: kustomize
  name: prescale-sample
spec:
  targetHpaName: nginx-project
  schedules:
    - cron: "55 * * * 6,0"
      percent: 165
    - cron: "55 0-1 * * 1-5"
      percent: 200
    - cron: "55 2-12 * * 1-5"
      percent: 500
    - cron: "55 13-23 * * 1-5"
      percent: 200 # To calculate new CPU AverageUtilization value based on formula: original * 100 / percent
  suspend: false
  revertWaitSeconds: 10
